---
- hosts: all
  sudo: yes
  user: vagrant
  vars:
#    dl_cdhrepo_file: ""
#    dl_cdhrepo_url: ""
#    default_proxy_url: ""
#    default_proxy_port: ""
#    default_proxy_username: ""
#    default_proxy_password: ""
#    default_proxy_env:
#      http_proxy: "http://{{ default_proxy_username }}:{{ default_proxy_password }}@{{ default_proxy_url }}:{{ default_proxy_port }}"
#      https_proxy: "http://{{ default_proxy_username }}:{{ default_proxy_password }}@{{ default_proxy_url }}:{{ default_proxy_port }}"
#    af_dev_gradle_opts: "-Dhttp.proxyHost={{ default_proxy_url }} -Dhttp.proxyPort={{ default_proxy_port }} -Dhttp.proxyUser={{ default_proxy_username }} -Dhttp.proxyPassword={{ default_proxy_password }} -Dhttps.proxyHost={{ default_proxy_url }} -Dhttps.proxyPort={{ default_proxy_port }} -Dhttps.proxyUser={{ default_proxy_username }} -Dhttps.proxyPassword={{ default_proxy_password }}"

  roles:
#    - ../common-roles/set-cdh-localrepofile
    - ../common-roles/set-cdh-repo
    - ../common-roles/cdh-pseudo-mr1
    - ../common-roles/asakusa-develop-setting
#    - ../common-roles/set-gradle-proxy
    - ../common-roles/af-bench-pos1-build
    - ../common-roles/af-bench-pos1-deploy-setting
