---
 - group: name={{ asakusa_dev_uname }}

 - user: name={{ asakusa_dev_uname }} shell=/bin/bash group={{ asakusa_dev_uname}} password="$1$yhrhUweC$Mid/XE2LZLaiSMjQlOZ/B/"

 - template: src=asakusa-develop_profile.j2 dest={{ asakusa_dev_uhome_dir }}/.asakusadev_profile
   become: yes
   become_user: "{{ asakusa_dev_uname }}"

 - lineinfile: dest={{ asakusa_dev_uhome_dir }}/.bash_profile line=". {{ asakusa_dev_uhome_dir }}/.asakusadev_profile"

 - name: Download Apach Hadoop pkg
   get_url: url={{ dl_ap_hadoop_url }} dest={{ dl_ap_hadoop_path }} mode=0755
   become: yes
   become_user: "{{ asakusa_dev_uname }}"

 - name: make asakusa home dir
   command: "mkdir -p {{ asakusa_home }}"
   become: yes
   become_user: "{{ asakusa_dev_uname }}"

 - name: uncompress Apach Hadoop pkg
   command: "tar -zxf {{ dl_ap_hadoop_path }}"
   become: yes
   become_user: "{{ asakusa_dev_uname }}"

 - name: make asakusa hadoop dir
   command: "mv {{ dl_ap_hadoop_version }} {{ asakusa_hadoop_dir }}"
   become: yes
   become_user: "{{ asakusa_dev_uname }}"

 - name: delete Apach Hadoop pkg
   command: "rm {{ dl_ap_hadoop_path }}"
   become: yes
   become_user: "{{ asakusa_dev_uname }}"

 - name: make asakusa work dir
   command: "mkdir -p {{ asakusa_work_dir }}"
   become: yes
   become_user: "{{ asakusa_dev_uname }}"
